//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationType
    {
        public OperationType()
        {
            this.OperationHistory = new HashSet<OperationHistory>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<OperationHistory> OperationHistory { get; set; }
    }
}
