//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.OperationHistory = new HashSet<OperationHistory>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string USERLogin { get; set; }
        public string USERPassword { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<OperationHistory> OperationHistory { get; set; }
    }
}
